---
- name: Install dependencies
  yum: name={{ item }}
  become: true
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add docker repo
  shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
  become: true
  args:
    chdir: "/etc/yum.repos.d"
    creates: docker-ce.repo

- name: Install docker
  yum: name=docker-ce
  become: true

- name: Restart docker
  systemd:
    name: docker.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: true

- name: Get docker-compose
  get_url: 
    url: "https://github.com/docker/compose/releases/download/1.5.1/docker-compose-{{ansible_system}}-{{ansible_machine}}"
    dest: /usr/local/bin/docker-compose
  register: get_compose
  become: true

- name: Add authority
  file:
    path: /usr/local/bin/docker-compose
    mode: "a+x"
  when: get_compose.changed
  become: true
