---
- name: Check kernel version.
  fail: msg="Kernel {{ ansible_kernel }} is not supported."
  when: "ansible_kernel is version('3.10', '<')"

- name: apt-get install packages
  apt:
    pkg: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common' ]
    state: present 
    update_cache: yes
  become: true

- name: Add Docker’s official GPG key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg

- name: define lsb_release -cs
  shell: lsb_release -cs
  ignore_errors: True
  register: lsb_release

- name: set up the stable repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"
  become: true

- name: Install docker-ce.
  apt: 
    pkg: [ 'docker-ce', 'docker-ce-cli', 'containerd.io' ]
    state: present 
    update_cache: yes
  become: true

- name: Get docker-compose
  get_url: 
    url: "https://github.com/docker/compose/releases/download/1.5.1/docker-compose-{{ansible_system}}-{{ansible_machine}}"
    dest: /usr/local/bin/docker-compose
  register: get_compose
  become: true

- name: Add authority
  file:
    path: /usr/local/bin/docker-compose
    mode: "a+x"
  when: get_compose.changed
  become: true
