---
- name: install development tools
  apt:
    pkg: [ 'zsh', 'tree', 'build-essential' ]
    state: latest
  become: yes

- name: install c++ development tools
  apt:
    pkg: [ 'cmake', 'clang', 'clang-format', 'cppcheck' ]
    state: latest
  become: yes

- name: install libs
  apt:
    pkg: [ 'libboost-all-dev', 'libpq-dev', 'libpqxx-dev']
    state: latest
  become: yes

- name: install document toosl
  apt:
    pkg: [ 'graphviz', 'imagemagick' ]
    state: latest
  become: yes

- name: install python tools
  apt:
    pkg: [ 'python3-pip' ]
    state: latest
  become: yes

- name: install pip tools
  pip:
    name: 
      - psycopg2
#      - tdqm
      - pydot
      - matplotlib
    executable: pip3
  become: yes
